Repository fiscozen/design_system, pull requests merged in 2024-08, with the labels that each got.

#102 LIB-601 feat(dropdown): ESC press closes dropdown
  packages/composables/package.json
  packages/composables/src/composables/index.ts
  packages/composables/src/composables/useKeyDown.ts
  packages/dropdown/package.json
  packages/dropdown/src/FzDropdown.vue
Labels: enhancement

#104 LIB-605 fix(alert): replaced createdAt as id with a true id
  packages/toast/src/FzToastQueue.vue
  packages/toast/src/queue.ts
  packages/toast/src/types.ts
Labels: bug

#103 LIB-636 feat(toast): open stack when new toast is enqueued
  apps/storybook/src/stories/ToastQueue.stories.ts
  packages/toast/package.json
  packages/toast/src/FzToastQueue.vue
  packages/toast/src/types.ts
Labels: enhancement

#108 LIB-654 refactor(dialog): backdrop click logic
  packages/composables/package.json
  packages/composables/src/composables/useClickOutside.ts
  packages/dialog/package.json
  packages/dialog/src/FzDialog.vue
  pnpm-lock.yaml
Labels: bug

#114 LIB-674 feat(simple-table): add FzColumn as subcomponent
  apps/storybook/src/stories/SimpleTable.stories.ts
Labels: documentation

#119 LIB-728 fix(typeahead): v-model
  apps/storybook/src/stories/Typeahead.stories.ts
  packages/typeahead/package.json
  packages/typeahead/src/FzTypeahead.vue
Labels: bug

#123 LIB-794 feat(select): render label only if it exists
  packages/select/package.json
  packages/select/src/FzSelect.vue
Labels: enhancement

#129 Token Story page
  apps/storybook/src/stories/Tokens.stories.ts
Labels: enhancement
