Repository fiscozen/design_system, pull requests merged in 2024-11, with the labels that each got.

#172 feat(navbar): add event emitter menuButtonClick
  packages/navbar/package.json
  packages/navbar/src/FzNavbar.vue
  packages/navbar/src/types.ts
Labels: enhancement

#161 feat: Improved storybook graphics and logo
  apps/storybook/.storybook/FiscozenTheme.ts
  apps/storybook/.storybook/manager.ts
  apps/storybook/package.json
  pnpm-lock.yaml
Labels: documentation, enhancement

#180 LIB-1457 fix(collapse): remove native arrow icon on webkit
  packages/collapse/package.json
  packages/collapse/src/FzCollapse.vue
Labels: bug

#179 LIB-1456 feat(navbar): xmark icon when menu is open
  packages/navbar/package.json
  packages/navbar/src/FzNavbar.vue
  packages/navbar/src/types.ts
Labels: enhancement

#185 fix(LIB-1475): navbar correct mobile breakpoint
  packages/navbar/package.json
  packages/navbar/src/FzNavbar.vue
  pnpm-lock.yaml
Labels: bug

#188 LIB-1437 fix(dialog): center dialog vertically
  packages/dialog/package.json
  packages/dialog/src/FzDialog.vue
Labels: bug
